geotrellis/vectorpipe

src/main/scala/vectorpipe/Clip.scala, src/main/scala/vectorpipe/VectorPipe.scala, src/main/scala/vectorpipe/osm/package.scala, src/main/tut/usage/concepts.md, src/main/tut/usage/usage.md
- ~~Log any `Left`s given from clipping~~ (logging is now framework agnostic)
We've decided to assume that exotic, non-cooperative geometries will always exist within OSM data. Rather than crash the whole ingest when one of these is encountered, this PR allows for these to be skipped over and logged. It should be possible to log any `Left` values encountered without incurring too much invasive `IO` - hopefully transfer of the failure string to the driver or a write to S3 will be enough.
**Question:** If we naively print a logging statement via each executor, will those be aggregated into the EMR log file already written to S3?
**Question:** Where to print the errors in the local case? It would be nice if a single solution took care of both the local and EMR cases.
Ping @lossyrob
=> Skip and log clipping failures

src/main/scala/vectorpipe/VectorPipe.scala, src/main/scala/vectorpipe/osm/Element.scala, src/main/scala/vectorpipe/osm/internal/ElementToFeature.scala, src/main/scala/vectorpipe/osm/package.scala, src/main/tut/usage/usage.md
We were silently skipping over failures to fuse `Line`s together in the depths of `ElementToFeature`. This PR adds a customizable way to log those failures, as well as reworks the APIs of the library's primary functions.
=> Add logging to `toFeatures`

ensime.sbt, project/plugins.sbt
Required for `sbt` subcommands to work appropriately with the configuration provided by `ensime.sbt`.
---
**Testing**
On `master`:
```
$ sbt publish-local
[info] Loading global plugins from /Users/hcastro/.sbt/0.13/plugins
[info] Loading project definition from /Users/hcastro/Projects/vectorpipe/project
[info] Updating {file:/Users/hcastro/Projects/vectorpipe/project/}vectorpipe-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[warn]
[warn]  * commons-io:commons-io:2.4 is selected over 1.3.1
[warn]      +- com.sksamuel.scrimage:scrimage-core_2.10:2.1.7     (depends on 2.4)
[warn]      +- org.apache.xmlgraphics:xmlgraphics-commons:2.1     (depends on …
```
=> Remove Ensime settings

build.sbt, src/main/scala/vectorpipe/Clip.scala, src/main/scala/vectorpipe/VectorPipe.scala
The `RDD[Geometry] => RDD[(SpatialKey, Geometry)]` logic was ported back to GeoTrellis, so now we need to use it.
=> Integrate ClipToGrid

src/main/scala/vectorpipe/osm/Element.scala, src/main/scala/vectorpipe/osm/package.scala
Some very old node data can contain bogus coordinates (`null`, for instance). This PR accounts for this.
Closes #30 .
=> Naughty Nodes

build.sbt, src/main/scala/vectorpipe/osm/Element.scala, src/main/scala/vectorpipe/osm/internal/ElementToFeature.scala, src/main/scala/vectorpipe/osm/internal/PlanetHistory.scala
Previously I wasn't respecting the original Node order when construction `Line`s. This resulted in some exception throwing in OSMesa.
=> Fix line order bug

src/main/scala/vectorpipe/Collate.scala, src/main/scala/vectorpipe/osm/Element.scala, src/main/scala/vectorpipe/osm/internal/ElementToFeature.scala, src/main/scala/vectorpipe/osm/internal/PlanetHistory.scala, src/main/scala/vectorpipe/osm/package.scala, src/test/scala/vectorpipe/CollateSpec.scala, src/test/scala/vectorpipe/osm/FeatureConstruction.scala
From suggestions from @mojodna .
The main change here is the combining of `ElementMeta` and `ElementData`. There wasn't a reason why they had to be apart, and the API is smaller now.
=> Minor API Tweaks

src/main/scala/vectorpipe/osm/internal/PlanetHistory.scala, src/main/scala/vectorpipe/osm/package.scala
**Note:** This doesn't yet include complex Polygons formed from relations - only simple ones from Ways. These are the vast majority.
=> Yield all (simple) Historical Features

build.sbt, src/main/scala/vectorpipe/VectorPipe.scala, src/main/scala/vectorpipe/osm/Element.scala, src/main/scala/vectorpipe/osm/internal/ElementToFeature.scala, src/main/scala/vectorpipe/osm/package.scala, src/test/scala/vectorpipe/osm/FeatureConstruction.scala
We had always done something like this on the Snapshot side, but we forgot to bring this detail over to the History code. If we don't include this logic, VectorPipe runs over country extracts will almost certainly run into degenerate Ways, which don't play well with later steps.
=> (history) Filter degenerate Polygons

src/main/scala/vectorpipe/osm/internal/PlanetHistory.scala
Nodes participating in the way being reconstructed were previously being credited rather than using metadata on the way itself. This resulted in way edits being credited to incorrect changesets (often much older).
This also reduces the set of candidate nodes associated with the way being reconstructed.
=> Credit subsequent edits

src/main/scala/vectorpipe/osm/Element.scala, src/main/scala/vectorpipe/osm/internal/PlanetHistory.scala
This assigns a `minorVersion` to each feature.
This is useful for a) distinguishing between edits of the element itself and those referred to and b) providing an additional component to use as a key when referring to specific geometry versions.
(This incorporates #41)
=> Minor versions

src/main/scala/vectorpipe/osm/Features.scala, src/main/scala/vectorpipe/osm/internal/ElementToFeature.scala, src/main/scala/vectorpipe/osm/internal/PlanetHistory.scala, src/main/scala/vectorpipe/osm/package.scala, src/main/tut/usage/osm.md, src/main/tut/usage/usage.md
This PR adds the `Features` type, a simple wrapper around the RDDs of various `Geometry` subtypes produced by the Elements-to-Features process. It's often the case that we want to inspect only a subset of the recreated features ("roads only", for instance). In these cases, we don't want to bother with Spark processing all the extra Points and Polygons. With the `Features` wrapper, it no longer will.
`Features` exposes the function `geometries: Features => RDD[OSMFeature]` as the glue to the rest of the VectorTile creation process, since the next step wants generic `OSMFeature`s.
The results of this PR should improve performance for OSMesa analytics generation, as well as other Azavea ingests that involve OSM data.
=> Separated Feature RDDs

build.sbt, src/main/scala/vectorpipe/osm/package.scala, src/main/scala/vectorpipe/package.scala, src/main/tut/usage/osm.md
And `useS3` along with it. It wasn't providing an advantage, and muddles the dependency graph.
=> Remove `hadoop-aws` dep

build.sbt
This PR adds more settings to the `publishSettings` in the `build.sbt`. This was done because before it was not possible to publish directly to binTray from `sbt` due to not having the the `binTrayRepository` set.
=> More Information for the publishSettings

.gitignore, src/main/scala/vectorpipe/LayerMetadata.scala
This fix makes possible the following code usage:
```scala
package vectorpipe
import geotrellis.spark._
import geotrellis.spark.tiling._
import geotrellis.spark.io._
import geotrellis.spark.io.file._
import geotrellis.spark.SpatialKey._
import geotrellis.spark.io.index.ZCurveKeyIndexMethod
import geotrellis.vector.{Feature, Geometry}
import geotrellis.vectortile.VectorTile
import geotrellis.util._
import org.apache.spark.rdd.RDD
object Test {
val layout: LayoutDefinition = ???
// val featGrid: RDD[(SpatialKey, Iterable[Feature[Geometry, String]])] = ???
val tiles: RDD[(SpatialKey, VectorTile)] =
vectortiles(Collate.byOSM, layout, null)
val bounds: KeyBounds[SpatialKey] =
tiles.map({ case (key, _) => KeyBounds(key, key) }).reduce(_ combine _)
/* Construct metadata for the Layer */
import …
```
=> Define a Full component for the LayerMetadata object

src/main/scala/vectorpipe/functions/osm/package.scala, src/main/scala/vectorpipe/functions/package.scala, src/main/scala/vectorpipe/internal/package.scala, src/main/scala/vectorpipe/relations/MultiPolygons.scala, src/main/scala/vectorpipe/relations/Routes.scala, src/main/scala/vectorpipe/vectortile/package.scala
So that they are all serialized correctly for Spark jobs.
Finally got around to cleaning up the diff in #69 and checking for other udf declarations at the object level. I _think_ I got them all? It would be worth a second eye to grep for missed instances.
Closes #69
=> Mark loggers and UDFs as transient lazy

src/main/scala/vectorpipe/vectortile/export/package.scala
I noticed while I was exporting tilesets to S3 that when I passed in a URI such as:
```
s3://geotrellis-test/foo/tiles-v01
```
that the tiles were saving to:
```
s3://geotrellis-test/foo/tiles-v0
```
As far as I can tell, it looks like the original intent of this code is to strip both leading and trailing slashes...or at least that's what works consistently when I pass URIs to `saveToS3`. So I modified the code to always remove leading + trailing slashes and to not accidentally remove other stuff.
=> Consistently strip leading + trailing slash from S3 URI prefix in export

.github/pull_request_template.md, CHANGELOG.md, README.md, RELEASING.md
I had started this after the 1.0.0-RC3 release and so when the discussion happened in #78 and #79 got created, that provided an additional kick to clean up and PR my notes right away.
There's also a CHANGELOG in here, I'm open to keeping or discarding whichever changes you all feel are most appropriate at this time.
@mojodna I attempted to adjust my list to match the suggested workflow you provided in https://github.com/geotrellis/vectorpipe/pull/78#issuecomment-486362399, as I like that better than what I did for RC3 (I attached the RC3 tag to master after merging the PR). The git flow paradigm essentially follows the bullets you laid out.
Closes #79 
Closes #77
=> Add RELEASING.md and a changelog

src/main/scala/vectorpipe/functions/osm/package.scala
Incorporate additional key/value pairs from `id-area-keys` for determining area-ness of a way.
Closes #74
=> Sync with id-area-keys@2.13.0

CHANGELOG.md, src/main/scala/vectorpipe/sources/AugmentedDiffSource.scala, src/main/scala/vectorpipe/sources/ChangeSource.scala, src/main/scala/vectorpipe/sources/ChangesetSource.scala
This lines up with the current approach to generating augmented diffs in overpass-diff-publisher. (Uncompressed diffs are still produced, but deprecated until this change can be rolled out.)
Refs https://github.com/azavea/osmesa/issues/122
=> Fetch gzipped augmented diff JSON

CHANGELOG.md, src/main/scala/vectorpipe/internal/package.scala, src/test/scala/vectorpipe/vectortile/PipelineSpec.scala
It can be helpful to know where a node was located immediately prior to deletion. It being no longer visible should serve as an indication not to use these coordinates unless needed.
=> Preserve deleted coordinates

CHANGELOG.md, src/main/scala/vectorpipe/sources/ChangesetSource.scala
`IOUtils.toString` without a character set has been deprecated.
=> Resolve commons-io deprecation warnings

CHANGELOG.md, src/main/scala/vectorpipe/functions/osm/package.scala, src/test/scala/vectorpipe/functions/osm/FunctionSpec.scala
Semicolon-delimited values are how tags with multiple values are represented in OSM. E.g. `shop=bakery;dairy` for a shop that sells both baked goods and dairy products.
When at least one value matches, the corresponding UDF returns `true`.
This also improves handling of falsy boolean values and expands the universe of waterway features.
Oh, and woo, tests.
=> Support for semicolon-delimited values

CHANGELOG.md, src/main/scala/vectorpipe/internal/package.scala
Not only are coordinates and tags dropped from elements that have been deleted (i.e. changed to `visible = false`), `nds` and `members` are also dropped. This populates them using the version immediately prior to the deletion, which allows deletes to be better tracked in various circumstances.
=> Populate deleted nds and members from previous version

src/main/scala/vectorpipe/relations/MultiPolygons.scala, src/main/scala/vectorpipe/relations/Routes.scala
This would have happened anyway, but this simplifies flow when reading.
=> Skip empty relations

src/main/scala/vectorpipe/vectortile/package.scala
When geometries are `null`, they should produce `null` reprojected geometries and empty lists of `SpatialKey`s.
=> Handle null geometries gracefully

src/main/scala/vectorpipe/VectorPipe.scala
With this change, runtime for `PipelineSpec` → "should generate multiple zoom levels" (which creates 2 intermediate levels) goes from ~70s to ~28s.
`PipelineSpec` → "should generate multiple layers" will fail without #97.
/cc @echeipesh @jpolchlo
=> Checkpoint intermediate levels to reduce re-calculation

src/main/scala/vectorpipe/VectorPipe.scala
Skip reprojection when source and target CRSes match.
=> Skip unnecessary reprojection

CHANGELOG.md, src/main/scala/vectorpipe/OSM.scala, src/main/scala/vectorpipe/functions/osm/package.scala, src/main/scala/vectorpipe/internal/package.scala, src/main/scala/vectorpipe/vectortile/export/package.scala, src/test/scala/vectorpipe/functions/osm/FunctionSpec.scala
Uninteresting tags are those that have little-to-no rendering relevance and shouldn't be considered when promoting nodes to points. The tag (and prefix) list was generated by querying for the top 200 single-use tags (i.e. the only tag applied to an element). `fixme`, `note`, and `source` are omitted, as they can be useful for validation and tracking.
=> Filter out uninteresting tags

build.sbt
When developing outside of an IDE, unused imports are difficult to track without warnings from the compiler. This enables said warnings.
=> Warn about unused imports

.travis.yml, src/main/scala/vectorpipe/internal/package.scala, src/test/scala/vectorpipe/MultiPolygonRelationReconstructionSpec.scala
Instantiating `Row`s with `GenericRowWithSchema` is awkward and requires defining a schema that should otherwise be implicitly determined. This replaces that pattern with one whereby a tuple is returned and converted into a `DataFrame` with appropriate column names.
`CHANGELOG` entry omitted due to this being an internals-only change.
=> Simplify by removing Row Encoders

src/main/scala/vectorpipe/OSM.scala, src/main/scala/vectorpipe/internal/package.scala, src/test/scala/vectorpipe/ProcessOSMTest.scala
Initialize JTS before using geometry functions. This prevents callers from needing to be aware of the `spark.withJTS` incantation.
=> Initialize JTS internally

README.md, project/Version.scala, src/main/scala/vectorpipe/VectorPipe.scala, src/main/scala/vectorpipe/functions/osm/package.scala, src/main/scala/vectorpipe/sources/AugmentedDiffSource.scala, src/main/scala/vectorpipe/sources/ChangesetMicroBatchReader.scala, src/main/scala/vectorpipe/sources/ChangesetReader.scala, src/main/scala/vectorpipe/sources/ChangesetSource.scala, src/main/scala/vectorpipe/vectortile/Pipeline.scala, src/main/scala/vectorpipe/vectortile/package.scala, src/test/scala/vectorpipe/sources/AugmentedDiffSourceTest.scala
Provides a hodgepodge of optimizations and fixes to minor issues encountered while attempting a global-scale ingest of vector tiles.
1. Prefer the use of `persist(MEMORY_AND_DISK)` to `localCheckpoint`.  Seems to speed up usage of `VectorPipe`.
2. Prevent empty geometries from hosing reprojection.
3. Prevent empty geometries from hosing keying to layout.
4. Remove unused imports.
=> Minor fixes and optimizations

CHANGELOG.md, src/main/scala/vectorpipe/sources/ReplicationStreamMicroBatchReader.scala
Streaming source sequence resolution rules are now:
1) `checkpoints` table (based on `Source.ProcessName`)
2) `Source.StartSequence` option
3) current remote sequence number
=> Fallback to the current sequence as a starting point

.gitignore, CHANGELOG.md, build.sbt, project/Dependencies.scala, project/Version.scala, src/main/scala/vectorpipe/OSM.scala, src/main/scala/vectorpipe/VectorPipe.scala, src/main/scala/vectorpipe/internal/package.scala, src/main/scala/vectorpipe/model/AugmentedDiff.scala, src/main/scala/vectorpipe/model/ElementWithSequence.scala, src/main/scala/vectorpipe/relations/Routes.scala, src/main/scala/vectorpipe/relations/utils/package.scala, src/main/scala/vectorpipe/sources/AugmentedDiffSource.scala, src/main/scala/vectorpipe/util/Geocode.scala, src/main/scala/vectorpipe/vectortile/Clipping.scala, src/main/scala/vectorpipe/vectortile/Pipeline.scala, src/main/scala/vectorpipe/vectortile/Simplify.scala, src/main/scala/vectorpipe/vectortile/export/package.scala, src/main/scala/vectorpipe/vectortile/package.scala, src/test/scala/vectorpipe/MultiPolygonRelationReconstructionSpec.scala, src/test/scala/vectorpipe/sources/AugmentedDiffSourceTest.scala, src/test/scala/vectorpipe/vectortile/LayerTestPipeline.scala, src/test/scala/vectorpipe/vectortile/TestPipeline.scala, src/test/scala/vectorpipe/vectortile/WeightedCentroid.scala
This PR upgrades to GT 3.0. There are a few significant changes that deserve special attention in this regard:
1. Spray -> Circe
2. Geotrellis Geometries -> JTS Geometries
3. AWS SDK V1 -> AWS SDK V2
4. Overriding dependencies to avoid test failures due to `jackson` version 2.9 colliding with Spark's `jackson` version
Closes #115
=> Upgrade to GT3.0 codebase

CHANGELOG.md, build.sbt, src/main/scala/vectorpipe/VectorPipe.scala, src/main/scala/vectorpipe/examples/AugmentedDiffProcessor.scala, src/main/scala/vectorpipe/examples/AugmentedDiffStreamProcessor.scala, src/main/scala/vectorpipe/examples/ChangeProcessor.scala, src/main/scala/vectorpipe/examples/ChangeStreamProcessor.scala, src/main/scala/vectorpipe/examples/ChangesetProcessor.scala, src/main/scala/vectorpipe/examples/ChangesetStreamProcessor.scala, src/test/scala/vectorpipe/TestEnvironment.scala
Add stream processing examples with `Source`, `Changeset`, etc to `vectorpipe.examples`. These examples lived in [azavea/osmesa](https://github.com/azavea/osmesa) but were moved here as part of https://github.com/azavea/osmesa/pull/177 since they really demonstrate VectorPipe functionality.
The old examples all constructed a consistent, default SparkSession. That was moved here as well, and is now provided as `VectorPipe.defaultSparkSessionWithJTS`.
I elected not to split VP into subprojects at this time, the list of examples doesn't feel large or comprehensive enough yet to warrant it. Instead I opened https://github.com/geotrellis/vectorpipe/issues/123 for the future.
You should be able to get these examples to run by following the docstring comment found in each.
=> Move VectorPipe examples from azavea/osmesa

src/main/scala/vectorpipe/model/ElementWithSequence.scala, src/main/scala/vectorpipe/sources/ChangeMicroBatchReader.scala, src/main/scala/vectorpipe/sources/ChangesetMicroBatchReader.scala
With these changes applied, I was able to run all six new examples in the `vectorpipe.examples` directory. These bugs were likely fallout from the GT 3.1 / Spark 2.4 upgrade and were only exposed with runnable examples in the project.
Run each of the examples using default arguments, they should now all pass. For example:
```
./sbt
> test:runMain test:runMain vectorpipe.examples.ChangesetStreamProcessor
```
For the AugmentedDiff examples you'll need to correctly set AWS_PROFILE and pass an s3 augmented diff location for `--augmented-diff-source`.
=> Fixup bugs in VectorPipe that prevent examples from running

README.md, RELEASING.md
Brings README + RELEASING markdown files up to date. I just ran through the `v2.1.0` release following these new instructions. 
Connects #120 
Closes #126
=> Documentation updates following CircleCI/Sonatype migration

src/main/scala/vectorpipe/sources/AugmentedDiffSource.scala
We need to catch the correct NoSuchKeyException from
the v2 client. We were catching a v1 client exception.
Bah. I missed one more. This gets the osmesa.apps.streaming.AOIMonitor fully working. Example run:
=> fixup: changed AWS SDK 404 exception in v2

src/main/scala/vectorpipe/sources/AugmentedDiffSource.scala
These 403s don't have a specific subclass,
so we catch the error that was thrown when
this code was run:
software.amazon.awssdk.services.s3.model.S3Exception:
Access Denied (Service: S3, Status Code: 403, Request ID: _)
Fallout from GT3.1 upgrade, we should have caught this exception
in #129 as well to properly refactor from VP 1.0 days.
No 404/403 errors from process run locally:
=> Catch S3 403s again in addition to 404s

src/main/scala/vectorpipe/internal/package.scala, src/test/scala/vectorpipe/ProcessOSMTest.scala
The README claims the String to Byte conversion or relation member `type` is "handled for you" in the top-level OSM object, but that is not the case.  So this PR adds a call to `ensureCompressedMembers` within `preprocessRelations` to the filtered `"relation"` records which will have non-empty `members` arrays.
Note: I figured it made sense to do this conversion when pre-processing input relations rather than only in the top-level OSM object (as the README claims).
See Issue https://github.com/geotrellis/vectorpipe/issues/134
The counts printed by `ProcessOSMTest` did not change after this change, and I removed the call to `ensureCompressedMembers` on the input test data since that would now be redundant.
Closes #134
=> Add call to ensureCompressedMembers in preprocessRelations

CHANGELOG.md, src/main/scala/vectorpipe/VectorPipe.scala
This PR changes the `Options` to be more general and accept any `Seq[LayoutLevel]` for the desired zoom levels.  The only constraints being that each level must define a unique zoom, and the tile layout for each level must be square `tileCols == tileRows`.  This allows VectorPipe to be used for different layout schemes other than the power-of-2 `ZoomedLayoutScheme`. One example use case would be for generating tiles matching the power-of-20 OpenLocationCode grid (my use case 😄).
The current `Options()` constructor was moved to a separate `apply` method which generates the `layoutLevels` using `ZoomedLayoutScheme` in the same way as before. So this change will  _probably_ not break any users BUT note that it will break for users that invoke the `new Options()` constructor directly rather …
=> Add support for any square layout level (not just from ZoomedLayoutScheme)

CHANGELOG.md, src/main/scala/vectorpipe/VectorPipe.scala, src/main/scala/vectorpipe/vectortile/Pipeline.scala, src/test/scala/vectorpipe/vectortile/LayerTestPipeline.scala, src/test/scala/vectorpipe/vectortile/TestPipeline.scala
* Adds `persist(vectorTiles: RDD[(SpatialKey, VectorTile)], zoom: Int)` method to the Pipeline with a default implementation simply passing the call to `saveVectorTiles(vectorTiles, zoom, pipeline.baseOutputURI)`
* Replaces call to `saveVectorTiles()` with `pipeline.persist()` (which by default _is_ `saveVectorTiles`)
* Changes return type of `VectorPipe.apply()` from `Unit` to `Map[Int, RDD[(SpatialKey, VectorTile)]]` as a map the generated VectorTile RDDs keyed by the zoom level for all `layoutLevels` defined in the options.
Reason for changes:
* let users override the behavior of saving the generated vector tiles
* let users access the generated vector tiles as they are when persisted as `RDD[(SpatialKey, VectorTile)]` 
This is useful for cases when additional processing outside the …
=> Add persist(vectorTiles, zoom) method to Pipeline to allow override

src/main/scala/vectorpipe/model/Changeset.scala
When reading from changeset XML files, latitude values were incorrectly read.
=> Fix changeset XML reads

CHANGELOG.md, project/Version.scala
We are currently lagging behind the GT release schedule.  This PR bumps up to parity.
=> Update Geotrellis version to 3.5.1

CHANGELOG.md, project/Version.scala, src/main/scala/vectorpipe/sources/AugmentedDiffMicroBatchReader.scala, src/main/scala/vectorpipe/sources/AugmentedDiffProvider.scala, src/main/scala/vectorpipe/sources/AugmentedDiffReader.scala, src/main/scala/vectorpipe/sources/AugmentedDiffSource.scala, src/main/scala/vectorpipe/sources/Source.scala, src/main/scala/vectorpipe/util/Implicits.scala, src/main/scala/vectorpipe/util/JsonRobustFeatureCollection.scala, src/main/scala/vectorpipe/util/JsonRobustFeatureCollectionMap.scala, src/main/scala/vectorpipe/util/RobustFeature.scala
While moving to https://github.com/azavea/onramp, it became necessary to handle diffs containing relations with faulty geometry, as Onramp will pass bad geometries through where Overpass will typically clean those geometries first.  This is useful as it allows one to see when bad relations are being created.
Additionally, we provide a means to plug in a error handler for when such bad geometries are encountered in the diff stream.
This PR is being opened against v1.1.0 due to a client still on the older version.  This PR will need to be brought forward into the v2 lineage, but will require a move to circe from spray.
=> Introduce robust augmented diff parsing

CHANGELOG.md, src/main/scala/vectorpipe/sources/ChangesetSource.scala
In `vectorpipe.sources.ChangesetSource`, there are a set of functions for locating a changeset in a replication stream corresponding to a given date.  These functions could fail for a variety of reasons, leading to unexplained `None.get` errors like
```
20/12/28 20:59:31 ERROR Client: Application diagnostics message: User class threw exception: java.util.NoSuchElementException: None.get
at scala.None$.get(Option.scala:347)
at scala.None$.get(Option.scala:345)
at vectorpipe.sources.ChangesetSource$.estimateSequenceNumber(ChangesetSource.scala:120)
at vectorpipe.sources.ChangesetSource$.findSequenceFor(ChangesetSource.scala:125)
...
```
These errors are transient, so hard to test.  The fixes taken up in this contribution are to attempt to define better fallback behavior.  For instance, when …
=> Improve robustness of changeset lookup

.github/docker-compose.yml, .github/workflows/ci.yml, CHANGELOG.md
This brief PR adds the machinery for using github actions to perform CI operations.
=> Use Github actions for CI
